In [2]:
import numpy as np

In [5]:
arr1 = np.ones((3,3))
arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
arr2 = np.zeros((2,3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
type(arr1)

numpy.ndarray

In [14]:
arr12 = np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [19]:
arr12[4:,2:]

array([[18, 19],
       [22, 23]])

In [33]:
arr3 = np.array(([1,2],[3,4],[4,6]))
arr3

array([[1, 2],
       [3, 4],
       [4, 6]])

In [37]:
arr5 = np.arange(24).reshape(6,4)
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [42]:
arr5[0:2,0:2]

array([[0, 1],
       [4, 5]])